# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Spring Microservice CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Start Build'     
        default: 'Yes'


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: docker.io
        server-username: ${{ secrets.DOCKER_USERNAME }}
        server-password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push User Service
      run: mvn package dockerfile:push --file user-service/pom.xml
